window.AUTOPASS_PATRIMONIO_VERSION='patrimonio-v12-0';
const $=x=>document.getElementById(x), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function getj(u){const r=await fetch(u,{cache:'no-store'}),j=await r.json();if(!r.ok||!j.ok)throw Error(j.error||'Falha');return j}
function locationCard(x){return `<article class="v7LocCard" data-loc="${x.id}"><div><span class="tag">${esc(x.company)} · ${esc(x.line)}</span><h3>${esc(x.location)}</h3></div><div class="v7MiniKpis"><b>${x.expected}<small>Previstos</small></b><b>${x.inventoried}<small>Inventariados</small></b><b>${x.missing}<small>Faltantes</small></b><b>${x.coverage_pct}%<small>Cobertura</small></b></div><div class="v7Flags"><span>${x.divergences} diverg.</span><span>${x.inoperative} inoper.</span><span>${x.media} mídias</span></div></article>`}
async function loadLocations(){const d=await getj('/api/v7/localidades');$('v7Locations').innerHTML=d.locations.map(locationCard).join('');document.querySelectorAll('[data-loc]').forEach(e=>e.onclick=()=>openLocation(e.dataset.loc))}
async function openLocation(id){const d=await getj('/api/v7/localidades/'+id),x=d.location;$('v7DetailTitle').textContent=`${x.location} · ${x.line}`;$('v7Detail').innerHTML=`<div class="v7DetailKpis"><b>${x.expected}<small>Previstos</small></b><b>${x.inventoried}<small>Inventariados</small></b><b>${x.missing}<small>Faltantes</small></b><b>${x.divergences}<small>Divergências</small></b><b>${x.media}<small>Mídias</small></b></div><h3>Equipamentos encontrados</h3><div class="v7Table">${x.equipment.map(e=>`<div><b>${esc(e.type)}</b><span>${esc(e.serial||e.identifier)}</span><span>${esc(e.status)}</span></div>`).join('')||'<p class="muted">Nenhum inventário formal.</p>'}</div><h3>Evidências e mídias da localidade</h3><div class="v7MediaGrid">${x.evidence_visits.flatMap(v=>(v.media||[]).map(m=>m.mime&&m.mime.startsWith('image/')?`<a href="${esc(m.url)}" target="_blank"><img loading="lazy" src="${esc(m.url)}" alt="${esc(m.name)}"
onerror="this.style.display='none';this.nextElementSibling.textContent='Mídia indisponível neste deploy · reimportar fonte'"><small>${esc(v.date||'')} · ${esc(v.author||'')}</small></a>`:`<a class="v7MediaFile" href="${esc(m.url)}" target="_blank">${esc(m.name)}</a>`)).join('')||'<p class="muted">Nenhuma mídia vinculada.</p>'}</div>`;$('v7DetailModal').classList.remove('hidden')}
async function search(){const q=$('v7Search').value.trim();if(q.length<2)return;const d=await getj('/api/v7/busca?q='+encodeURIComponent(q));$('v7SearchResults').innerHTML=`<h3>Localidades</h3>${d.locations.map(x=>`<button class="v7Result" data-loc="${x.id}">${esc(x.location)} · ${esc(x.line)}</button>`).join('')||'<span class="muted">Nenhuma.</span>'}<h3>Equipamentos da base</h3>${d.assets.map(x=>`<button class="v7Result" data-asset="${x.id}">${esc(x.type)} · ${esc(x.serial||x.asset_key)} · ${esc(x.locality||'')}</button>`).join('')||'<span class="muted">Nenhum.</span>'}`;document.querySelectorAll('[data-loc]').forEach(e=>e.onclick=()=>openLocation(e.dataset.loc));document.querySelectorAll('[data-asset]').forEach(e=>e.onclick=()=>openAsset(e.dataset.asset))}
async function openAsset(id){const d=await getj('/api/v7/equipamentos/'+id),x=d.asset;$('v7DetailTitle').textContent=`${x.type||'Equipamento'} · ${x.serial||x.asset_key||''}`;$('v7Detail').innerHTML=`<div class="v7Asset"><p><b>Base:</b> ${esc(x.company)} · ${esc(x.line)} · ${esc(x.locality)}</p><p><b>Modelo:</b> ${esc(x.model||'—')} · <b>Fornecedor:</b> ${esc(x.supplier||'—')}</p><p><b>Último inventário:</b> ${x.latest_inventory?esc((x.latest_inventory.location||'')+' · '+(x.latest_inventory.status||'')):'Não encontrado em inventário'}</p><h3>Histórico</h3>${x.history.map(h=>`<div class="historyRow"><span>${esc(h.created_at||'')}</span><b>${esc(h.status||'')}</b><span>${esc(h.divergence||'')}</span></div>`).join('')||'<p class="muted">Sem histórico.</p>'}</div>`;$('v7DetailModal').classList.remove('hidden')}
$('v7SearchBtn').onclick=search;$('v7Search').onkeydown=e=>{if(e.key==='Enter')search()};$('v7Close').onclick=()=>$('v7DetailModal').classList.add('hidden');loadLocations().catch(console.error);

async function loadV12(){try{const [s,l]=await Promise.all([getj('/api/v12/resumo'),getj('/api/v12/localidades')]);
$('v12Kpis').innerHTML=`<article><span>Confiabilidade média</span><b>${s.average_score}%</b></article><article class="good"><span>Confiáveis</span><b>${s.reliable}</b></article><article class="warn"><span>Atenção</span><b>${s.attention}</b></article><article class="bad"><span>Críticas</span><b>${s.critical}</b></article><article><span>Faltantes</span><b>${s.missing}</b></article><article><span>Divergências</span><b>${s.divergences}</b></article>`;
$('v12Locations').innerHTML=l.locations.slice(0,18).map(x=>`<button class="v12IntelLoc ${x.level.toLowerCase()}" data-v12loc="${x.id}"><span><b>${esc(x.location)}</b><small>${esc(x.company)} · ${esc(x.line)}</small></span><strong>${x.score}%</strong><em>${x.missing} falt. · ${x.divergences} diverg.</em></button>`).join('');document.querySelectorAll('[data-v12loc]').forEach(e=>e.onclick=()=>openLocation(e.dataset.v12loc));}catch(e){console.error(e)}}
if($('v12Refresh'))$('v12Refresh').onclick=loadV12;loadV12();
